--Q1. Which Locations Generate the Highest Revenue?
SELECT
    location,
    ROUND(SUM(purchase_amount_inr) / 1000000.0, 2) || ' M' AS total_revenue,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount_inr),2) AS avg_purchase
FROM customer_data
GROUP BY location
ORDER BY SUM(purchase_amount_inr) DESC;

--Q2. Which Product Categories Generate the Highest Revenue?
SELECT
    category,
    ROUND(SUM(purchase_amount_inr) / 1000000.0,2) || ' M' AS total_revenue,
    COUNT(customer_id) AS total_orders,
    ROUND(AVG(review_rating::numeric),2) AS avg_rating
FROM customer_data
GROUP BY category
ORDER BY SUM(purchase_amount_inr) DESC;

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased as products, ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating"
from customer_data
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4. Which Payment Method Generates the Highest Revenue and Average Purchase Amount?
SELECT
    payment_method,
    ROUND(SUM(purchase_amount_inr) / 1000000.0, 2) || ' M' AS total_revenue,
    ROUND(AVG(purchase_amount_inr) / 1000.0, 2) || 'K' AS avg_purchase_amount,
    COUNT(customer_id) AS total_orders
FROM customer_data
GROUP BY payment_method
ORDER BY SUM(purchase_amount_inr) DESC;

--Q5. Which Season Generates the Highest Revenue?
SELECT
    season,
    ROUND(SUM(purchase_amount_inr) / 1000000.0, 2) || ' M' AS total_revenue
FROM customer_data
GROUP BY season
ORDER BY SUM(purchase_amount_inr) DESC;
----------------------------------------------------------------


--Q6. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as "Total customers",
ROUND(AVG(purchase_amount_inr)/ 1000.0, 2) || 'K' as "Avg Spend",
Round(SUM(purchase_amount_inr) / 1000000.0, 2) || 'M' as "Total Revenue"
from customer_data
group by subscription_status
order by "Total Revenue", "Avg Spend" desc;

--Q7. What is the total revenue generated by male vs. female customers?
select gender, ROUND(SUM(purchase_amount_inr) / 1000000.0, 2) || 'M' as "Revenue (INR)"
from customer_data
group by gender

--Q8. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer_data
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
order by "Number of Customers" desc

--Q9. What is the distribution of customers across different purchase frequency groups?
SELECT
    frequency_of_purchases,
    COUNT(customer_id) AS total_customers,
    ROUND(
        COUNT(customer_id) * 100.0 /
        (SELECT COUNT(*) FROM customer_data),
        2
    ) || '%' AS percentage
FROM customer_data
GROUP BY frequency_of_purchases
ORDER BY COUNT(customer_id) DESC;

--Q10. What is the revenue contribution of each age group?
select age_group,
ROUND(SUM(purchase_amount_inr)/ 1000000.0, 2) || 'M' as total_revenue
from customer_data
group by age_group
order by total_revenue desc;

